name: "[Shared] Build golang action"
on:
  workflow_call:
    inputs:
      service_name:
        description: "Name of the microservice"
        required: true
        type: string
      artifact_name:
        description: "Artifacts to upload"
        required: false
        type: string
        default: false
      artifact_path:
        description: "Artifacts to upload"
        required: false
        type: string
        default: false
    secrets:
      TEAM_PAT:
        required: true
env:
  GOPRIVATE: github.com/cardalpha
  GH_ACCESS_TOKEN: ${{ secrets.TEAM_PAT }}

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEAM_PAT }}
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"

      - run: go version
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Install dependencies
        run: go mod tidy

      - name: test
        run: go test ./...

      - name: Go build
        run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o out/${{ inputs.service_name }}

      - if: inputs.artifact_path != '' && inputs.artifact_name != ''
        name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
